### ISSUE TITLE
Header/Footer: Set Footer email to open up email client on click

### ISSUE THREAD

**Issue by iksoosong** [International-Mentorship-ISMP/ismp#134] opened 2020-06-13 04:29 UTC
Clicking on the "Contact Us" button in the footer should open up an email client. In html, you can do:
`emailto:info@internationalmentorship.org` not sure what the react equivalent is

**Comment by dbtung** [comment] 2020-06-14 00:02
Duplicate of #159

**Closed by dbtung** 2020-06-14 00:02 UTC
Labels: comp/header/footer
