### ISSUE TITLE
Google Analytics Implementation

### ISSUE THREAD

**Issue by jessewoo** [International-Mentorship-ISMP/ismp#119] opened 2020-06-13 00:44 UTC

**Comment by jessewoo** [comment] 2020-06-13 00:45
Throw GA script to header. Tracking purposes.

**Comment by JonSEng** [comment] 2020-06-15 06:27
Hi @jessewoo jw is this a duplicate of https://github.com/International-Mentorship-ISMP/ismp/issues/12

**Comment by iksoosong** [comment] 2020-06-18 06:38
duplicate as mentioned ^

**Closed** 2020-06-18 06:37 UTC
